// app/pages/work.vue
<script lang="ts" setup>
defineOgImageComponent('Main', {
  description: 'My work',
  title: 'Work',
})
</script>

<template>
  <div class="flex flex-col gap-16">
    <WorkCard>
      <template #title>
        reskin
      </template>
      <template #links>
        <UButton as-child>
          <NuxtLink to="https://github.com/jvxz/reskin" target="_blank" class="flex items-center gap-2">
            <Icon name="simple-icons:github" class="-translate-y-0.5" />
            Source
          </NuxtLink>
        </UButton>
        <UButton as-child>
          <NuxtLink to="https://reskin.im" target="_blank" class="flex items-center gap-2">
            <Icon name="tabler:link" class="-translate-y-0.5" />
            Website
          </NuxtLink>
        </UButton>
      </template>
      <template #subtitle>
        creator, maintainer ⋅ jul. 2025 ─ present
      </template>
      <template #description>
        Advanced Minecraft skin management
      </template>
      <template #stack>
        <Icon title="Nuxt" name="simple-icons:nuxt" />
        <Icon title="Drizzle" name="simple-icons:drizzle" />
        <Icon title="Three.js" name="custom:three" />
        <Icon title="Microsoft" name="simple-icons:microsoft" />
      </template>
    </WorkCard>
    <WorkCard>
      <template #title>
        overcast
      </template>
      <template #subtitle>
        creator, maintainer ⋅ feb. 2025 ─ present
      </template>
      <template #description>
        Simple SoundCloud archival web app
      </template>
      <template #links>
        <UButton as-child>
          <NuxtLink to="https://github.com/jvxz/overcast" target="_blank" class="flex items-center gap-2">
            <Icon name="simple-icons:github" class="-translate-y-0.5" />
            Source
          </NuxtLink>
        </UButton>
        <UButton as-child>
          <NuxtLink to="https://overcast.jamie.to" target="_blank" class="flex items-center gap-2">
            <Icon name="tabler:link" class="-translate-y-0.5" />
            Website
          </NuxtLink>
        </UButton>
      </template>
      <template #stack>
        <Icon title="Nuxt" name="simple-icons:nuxt" />
        <Icon title="Redis" name="simple-icons:redis" />
        <Icon title="MinIO" name="simple-icons:minio" />
      </template>
    </WorkCard>
    <WorkCard>
      <template #title>
        otio
      </template>
      <template #subtitle>
        creator, maintainer ⋅ jun. 2025 ─ present
      </template>
      <template #description>
        Elegant inactivity timeout for your development servers
      </template>
      <template #links>
        <UButton as-child>
          <NuxtLink
            to="https://github.com/jvxz/otio"
            target="_blank"
            class="flex items-center gap-2"
          >
            <Icon name="simple-icons:github" class="-translate-y-0.5" />
            Source
          </NuxtLink>
        </UButton>
        <UButton as-child>
          <NuxtLink
            to="https://www.npmjs.com/package/otio"
            target="_blank"
            class="flex items-center gap-2"
          >
            <Icon name="simple-icons:npm" class="-translate-y-0.5" />
            npm
          </NuxtLink>
        </UButton>
      </template>
      <template #stack>
        <Icon title="Node.js" name="simple-icons:nodedotjs" />
        <Icon title="Zod" name="simple-icons:zod" />
        <Icon title="Effect" name="custom:effect" />
      </template>
    </WorkCard>
    <WorkCard>
      <template #title>
        esgist
      </template>
      <template #subtitle>
        creator, maintainer ⋅ apr. 2025 ─ present
      </template>
      <template #description>
        Generate an ESLint config from a GitHub Gist
      </template>
      <template #links>
        <UButton as-child>
          <NuxtLink
            to="https://github.com/jvxz/esgist"
            target="_blank"
            class="flex items-center gap-2"
          >
            <Icon name="simple-icons:github" class="-translate-y-0.5" />
            <p>Source</p>
          </NuxtLink>
        </UButton>
        <UButton as-child>
          <NuxtLink
            to="https://www.npmjs.com/package/esgist"
            target="_blank"
            class="flex items-center gap-2"
          >
            <Icon name="simple-icons:npm" class="-translate-y-0.5" />
            <p>npm</p>
          </NuxtLink>
        </UButton>
      </template>
      <template #stack>
        <Icon title="Node.js" name="simple-icons:nodedotjs" />
        <Icon title="Vitest" name="simple-icons:vitest" />
        <Icon title="Effect" name="custom:effect" />
      </template>
    </WorkCard>
  </div>
</template>

// src/app/work/page.tsx
import type { Metadata } from 'next'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Work',
  description: 'Jamie\'s work!',
  icons: {
    icon: 'https://github.com/jvxz.png',
  },
}

export default function Page() {
  return (
    <article className="prose">
      <section className="space-y-16">
        <WorkCard
          sourceUrl="https://github.com/jvxz/ezra"
          webUrl="https://ezra.jamie.to"
        >
          <h1 className="font-mono">ezra</h1>
          <p className="text-muted-foreground text-sm">
            creator, maintainer
            <span className="font-bold">⋅</span>
            {' '}
            jan. 2025 ─ present
          </p>
          <p>Modern, fast, local-first time tracker for RaterHub workers.</p>
        </WorkCard>
        <WorkCard
          sourceUrl="https://github.com/jvxz/mieru"
          webUrl="https://mieru.jamie.to"
        >
          <h1 className="font-mono">mieru</h1>
          <p className="text-muted-foreground text-sm">
            creator, maintainer
            <span className="font-bold">⋅</span>
            {' '}
            feb. 2025 ─ present
          </p>
          <p>
            Beautiful, opinionated fork of
            <Link
              href="https://ui.shadcn.com"
              target="_blank"
            >shadcn/ui
            </Link>
            .
          </p>
        </WorkCard>
        <WorkCard
          sourceUrl="https://github.com/jvxz/esgist"
          webUrl="https://www.npmjs.com/package/esgist"
        >
          <h1 className="font-mono">esgist</h1>
          <p className="text-muted-foreground text-sm">
            creator, maintainer
            <span className="font-bold">⋅</span>
            {' '}
            apr. 2025 ─ present
          </p>
          <p>Easily convert your GitHub Gist to an ESLint config via a CLI.</p>
        </WorkCard>
      </section>
    </article>
  )
}

function WorkCard({ children, className, sourceUrl, webUrl }: { children: React.ReactNode, className?: string, sourceUrl: string, webUrl: string }) {
  return (
    <div className={cn('prose relative !space-y-2', className)}>
      {children}
      <div className="absolute right-0 bottom-0 my-1 flex items-center gap-2">

      </div>
      <div className="absolute top-0 right-0 my-1 flex items-center gap-2">
        <Button
          className="flex items-center gap-2"
          asChild
        >
          <Link
            className="!no-underline"
            href={webUrl}
            target="_blank"
          >
            Website
            <span className="iconify icon-[mingcute--globe-2-fill]"></span>
          </Link>
        </Button>
        <Button
          className="flex items-center gap-2"
          asChild
        >
          <Link
            className="!no-underline"
            href={sourceUrl}
            target="_blank"
          >
            Source
            <span className="iconify icon-[mingcute--github-fill]"></span>
          </Link>
        </Button>

      </div>
    </div>
  )
}
