// app/components/app/header.vue
<template>
  <header class="mt-24 flex items-center gap-2 border-black text-black">
    <p class="font-bold tracking-widest text-primary select-none">
      (•◡•)
    </p>
    <div class="ml-auto" />
    <UButton :variant="$route.path === '/' ? 'active' : 'default'">
      <NuxtLink to="/">
        Profile
      </NuxtLink>
    </UButton>
    <UButton :variant="$route.path === '/work' ? 'active' : 'default'">
      <NuxtLink to="/work">
        Work
      </NuxtLink>
    </UButton>
    <UButton :variant="$route.path === '/uses' ? 'active' : 'default'">
      <NuxtLink to="/uses">
        Uses
      </NuxtLink>
    </UButton>
    <UButton :variant="$route.path === '/time' ? 'active' : 'default'">
      <NuxtLink to="/time">
        Time
      </NuxtLink>
    </UButton>
  </header>
</template>

// src/components/layout/header.tsx
import { ActiveLink } from '../active-link'

export const routes = [
  {
    label: 'Profile',
    href: '/',
  },
  {
    label: 'Work',
    href: '/work',
  },
  {
    label: 'Uses',
    href: '/uses',
  },
  {
    label: 'Time',
    href: '/time',
  },
]

function LayoutHeader() {
  return (
    <header className="my-16 flex items-center justify-between">
      <div className="text-primary font-bold tracking-widest select-none">
        <ActiveLink
          dataActive={false}
          href="/"
        >
          <span className="font-bold">(•◡•)</span>
        </ActiveLink>
      </div>
      <ul className="flex items-center gap-2">
        {routes.map(route => (
          <li key={route.href}>
            <ActiveLink href={route.href}>
              {route.label}
            </ActiveLink>
          </li>
        ))}
      </ul>
    </header>
  )
}

export { LayoutHeader }
