// src/app/time/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import { Suspense } from 'react'
import { FilterTabs } from './components/filter-tabs'
import { FilteredContent, FilteredContentFallback } from './components/filtered-content'

export const metadata: Metadata = {
  title: 'Time',
  description: 'My time spent coding! (since Apr 13, 2025)',
  icons: {
    icon: 'https://github.com/jvxz.png',
  },
}

export default function Page() {
  return (
    <article className="flex flex-col gap-4">
      <div className="flex gap-3">
        <h1 className="font-mono text-2xl">time</h1>
        <p className="text-muted-foreground self-end font-mono text-sm">est. Apr 13, 2025</p>
      </div>
      <FilterTabs />
      <Suspense fallback={<FilteredContentFallback />}>
        <FilteredContent />
      </Suspense>
      <p className="text-muted-foreground text-right text-sm">
        Data collected from
        {' '}
        <Link
          href="https://wakatime.com"
          target="_blank"
          className="text-primary underline"
        >
          WakaTime
        </Link>
        .
      </p>
    </article>
  )
}

// app/pages/time.vue
<script lang="ts" setup>
defineOgImageComponent('Main', {
  description: 'My time I\'ve spent on programming, sourced from Wakapi',
  title: 'Time',
})

const isPending = ref(false)
</script>

<template>
  <section class="flex flex-col gap-8">
    <div class="flex flex-col gap-6">
      <div class="flex justify-between">
        <h1 class="font-mono text-3xl font-medium">
          time <span class="text-sm font-normal text-muted-foreground">est. Apr 13, 2025</span>
        </h1>
        <USpinner v-if="isPending" class="size-8 text-primary" />
      </div>
      <div class="flex items-center gap-1">
        <TimeSpanButton
          v-for="span in timeSpanOptions"
          :key="span"
          :span="span"
        />
      </div>
    </div>
    <TimeSpanInfo @is-pending="isPending = $event" />
    <p class="self-end text-sm font-normal text-muted-foreground">
      Data gathered from
      <NuxtLink
        href="https://wakapi.dev"
        target="_blank"
        class="text-primary underline"
      >
        Wakapi
      </NuxtLink>
    </p>
  </section>
</template>
